### ISSUE TITLE
Stats guide - graph of stat ratios

### ISSUE THREAD

**Issue by m1s3ri** [stormearthandlava/stormearthandlava.github.io#15]
I believe it would be beneficial to include a visual guide of the way secondary stats are split. Highcharts would be good for stylistically matching other content on the site, but MS Office or many other various tools could be used to quickly and easily generate a visual for something that should only need to be updated once per patch.

For maximum ease, the graph could also feature actual example values of an ideal breakdown at a given ilv (Heroic raid, Mythic raid, etc). Toggleable views across a small variety of relevant item levels.

Linked, unstyled draft of Excel pie chart. https://imgur.com/a/lX71NHV

**Comment by kpey** [comment]
Thanks for the suggestion, we'll discuss what we can do to make the stat ratios more accessible and visually interesting.
