### ISSUE TITLE
Guide pages - talents

### ISSUE THREAD

**Issue by kpey** [stormearthandlava/stormearthandlava.github.io#2]
8.0 talent discussion and suggestions need to be written up.

# TODO
- Tier by tier discussion of talents
- Suggested talent setups with variants
- Talent simulations @Bloodmallet we will wait a little bit for sims in case we get some adjustment between now and 8.0

**Comment by Bloodmallet** [comment]
prepared talent page with some structure

https://github.com/stormearthandlava/stormearthandlava.github.io/commit/9cc599edf964e732e46da227e6b533ed302a4e6c

**Comment by kpey** [comment]
First pass at talent page completed

bd7cfd2e54318953303467ca5c3096cd2b4a4df7

**Comment by kpey** [comment]
Finished in 1370b83e6b133795d70e06af66793eb04d90bcc2.
