### ISSUE TITLE
Guide pages - priority list

### ISSUE THREAD

**Issue by kpey** [stormearthandlava/stormearthandlava.github.io#3]
8.0 priority list discussion and suggestions need to be written up.

# TODO
- APL optimisation for more accurate priority lists
- Talent additions to the list (small amount of JS)
- ST/AOE differences
- Opener? Might as well.

**Comment by Bloodmallet** [comment]
Latest APL can be found here: https://github.com/simulationcraft/simc/blob/bfa-dev/engine/class_modules/sc_shaman.cpp#L7119

**Comment by Bloodmallet** [comment]
Added current work in progress apl to page

https://github.com/stormearthandlava/stormearthandlava.github.io/commit/e7facc4d4e4cee2452a181441426b9940e884de1
