### ISSUE TITLE
Guide pages - stats

### ISSUE THREAD

**Issue by kpey** [stormearthandlava/stormearthandlava.github.io#4]
8.0 *prepatch* stat discussion needs to be written up.

# TODO
- Consider if we need to re-think how we present stat ratios
- Consider if we need multiple stat ratios
- Bloodystats can be a last minute thing @Bloodmallet

**Comment by Bloodmallet** [comment]
polished stats page with extending feature for advanced information. added enchants and gems to the page

https://github.com/stormearthandlava/stormearthandlava.github.io/commit/d90ab475b1c25b5b82498746123c65a4fe863cac

**Comment by kpey** [comment]
Per discussion yesterday, we'll be structuring this page (and other pages) in the following format:

*Brief, basic blurb*
**Information (stat ratios, talents etc)
*Advanced/in depth discussion*

To aid with users finding information more easily.

**Comment by Bloodmallet** [comment]
An example for an advanced information implementation can be found [in the wiki](https://github.com/stormearthandlava/stormearthandlava.github.io/wiki#adding-advanced-information).
