### ISSUE TITLE
Guide pages - trinkets

### ISSUE THREAD

**Issue by kpey** [stormearthandlava/stormearthandlava.github.io#5]
8.0 trinket lists need calculation.

# TODO
- Continue researching bloodytrinket integration however you see fit @Bloodmallet

**Comment by Bloodmallet** [comment]
I'll be exploring the import of the json files from bloodmallet.com directly. This way they will be as up to date as possible. The charts will show a time stamp, imported from the json, so we won't need to update the page timestamp each week.
